### PR TITLE
Added GitHub tutorial

### PR DESCRIPTION
**Pull request by josephkhawly**

### CODE REVIEW

**Comment by scottopell** [comment]
Looks like a great start! Assuming you're still going on this, so some early feedback would be to leave the git stuff to the git tutorial.

I would say that the confusing part about github is figuring out the github specific terminology (such as forking, starring, following etc)

Then a natural bridge between the two would be something along the lines of
> as mentioned in the [git](#) tutorial, you can work with remote repositories. Github (and BitBucket) are two of the most popular examples of remotes for your git repositories

Or something along these lines.

And idk about the android studio tutorial, what are the plans for that? like getting a hello, world app written and built or something like that? Or just downloading everything and not setting up emulators/adb etc?

**Comment by josephkhawly** [comment]
Thanks for the feedback, Scott. For the Android Studio tutorial, I was probably thinking about doing the second option, as well as downloading the emulators and adb.

**Comment by leviathan747** [comment]
Is this ready to be pulled in or do you need more time to do the Android Studio tutorial?

My comments:
Good stuff so far. I suggest defining pull request among your terminology. Also it would be good if you explained under the section for creating a repo that you can choose the option to initialize a repo with a README. This is a simpler way for beginners so they don't have to mess with remotes directly.

**Comment by josephkhawly** [comment]
I do need to finish the Android Studio tutorial, so it can't be pulled in just yet.

**Comment by jay-hankins** [comment]
@josephkhawly Would you like to finish up your Android studio tutorial?

**Pull request closed without merging**
