### PR TITLE
Update lab5 for CS 177 students

### PR DESCRIPTION
**Pull request by spencer-brown**
@leviathan747 can you please check this over and see if there are an edits you want to make?

### CODE REVIEW

**Comment by scottopell** [comment]
Have them use `pdb`.

It's the industry standard python debugger.

**Comment by leviathan747** [comment]
@scottopell is that available on the CS lab machines

**Comment by scottopell** [comment]
Very good question. I don't know

**Comment by leviathan747** [comment]
Looks like you have to use python at runtime, import the pdb module, your module, and then run pdb.run() https://docs.python.org/2/library/pdb.html

**Comment by scottopell** [comment]
Yes, it is. Its hard for me to test because I've hit the CS file quota haha.

But what you do is `import "pdb"`, its part of the standard lib. Then you can do breakpoints with `pdb.set_trace()`.

You can also use `pdb.run()` as you mentioned.

Another option is to invoke it directly from the CLI, `python -m pdb filename.py` according to the docs, but I've never used it this way personally. That would seem to be the most similar to jdb and gdb though.

**Comment by leviathan747** [comment]
I don't know enough about pdb to write instructions on this. Do we have anyone who could add this part?

**Comment by spencer-brown** [comment]
Based on what Harris said, they don't really need to set any breakpoints. Can we go ahead and ship this as-is before any other 177 students/190 TAs get really confused?

It sounds like we should definitely incorporate pdb in the future.

**Comment by leviathan747** [comment]
Go ahead and ship. We need to add pdb in the future definitely because
otherwise there's no debugging tool. It'd just be debugging practice.

**Pull request merged**
